[package]
name = "keyserver"
version = "0.2.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"
description = "Cash:web Keyserver is a Bitcoin public key and metadata registry"

[features]
monitoring = ["prometheus", "prometheus-static-metric"]

[dependencies]
async_zmq = "0.3.1"
base64 = "0.12.0"
bitcoin = "0.23.0"
bitcoincash-addr = "0.5.2"
bitcoin_hashes = "0.7.6"
bytes = "0.5.4"
cashweb = "0.1.0-alpha.3"
clap = { version = "2.33.0", features = ["yaml"] }
config = "0.10.1"
dashmap = "3.11.1"
dirs = "2.0.2"
futures = "0.3.4"
hex = "0.4.2"
http = "0.2.1"
hyper = "0.13.5"
lazy_static = "1.4.0"
log = "0.4.8"
pretty_env_logger = "0.4.0"
prost = "0.6.1"
prometheus = { version = "0.8.0", optional = true }
prometheus-static-metric = { version = "0.2.0", optional = true }
rand = "0.7.3"
rocksdb = "0.13.0"
secp256k1 = { version = "0.17.2", features = ["rand-std"] }
serde = { version = "1.0.106", features = ["derive"] }
sha2 = "0.8.1"
subtle = "2.2.2"
tokio = { version = "0.2.18", features = ["blocking",  "macros", "rt-core", "rt-threaded", "sync", "time"] }
url = "2.1.1"
warp = "0.2.2"
